### PR TITLE
Paginate artists, venues, and notes pages

### LINKED ISSUE #9: Paginate the venue, artist and note list pages instead of displaying everything
The notes page, artist page, and venue page, currently display everything. What if there are 10,000 notes? Display a sensible number of items. Use pagination for these pages and the search results.

### PR DESCRIPTION
**Pull request by cjdufault**
Closes #9 -- Paginate the venue, artist and note list pages instead of displaying everything

### CODE REVIEW

**Review by NateBigStone — CHANGES_REQUESTED** [review]
Seems to work, I don't have a lot of test data, though.
I think there's a slight merge conflict that needs to be addressed and we'll be good.

**Comment by cjdufault** [comment]
Resolved!

**Review by NateBigStone — APPROVED** [review]

**Comment by NateBigStone** [comment]
@cjdufault 👍

**Comment by yp0975eu** [comment]
Do you think something like this needs tests?

**Review by yp0975eu — APPROVED** [review]

**Pull request merged**
